connector.name=delta_lake

# 1. External Hive Metastore Connection
hive.metastore=thrift
hive.metastore.uri=thrift://hive:9083

fs.s3.enabled=true

# 2. Native AWS S3 Storage Provider
s3.aws-access-key=admin
s3.aws-secret-key=password
s3.region=us-east-1
s3.endpoint=http://minio:9000
s3.path-style-access=true