-- YCSB LakeVilla
DROP NAMESPACE ycsb CASCADE;

CREATE NAMESPACE ycsb;

CREATE TABLE spark_catalog.ycsb.usertable (YCSB_KEY VARCHAR(255),FIELD0 String, FIELD1 String,FIELD2 String, FIELD3 String,FIELD4 String, FIELD5 String,FIELD6 String, FIELD7 String,FIELD8 String, FIELD9 String) USING delta;

-- YCSB Spark-Delta
DROP NAMESPACE ycsbsparkdl CASCADE;

CREATE NAMESPACE ycsbsparkdl;

CREATE TABLE spark_catalog.ycsbsparkdl.usertable (YCSB_KEY VARCHAR(255),FIELD0 String, FIELD1 String,FIELD2 String, FIELD3 String,FIELD4 String, FIELD5 String,FIELD6 String, FIELD7 String,FIELD8 String, FIELD9 String) USING delta;

-- Banking LakeVilla
DROP NAMESPACE banking CASCADE;
CREATE NAMESPACE banking;
CREATE TABLE spark_catalog.banking.banking0 (Banking_ID string, balance string) USING delta;

INSERT INTO spark_catalog.banking.banking0 VALUES ("0", "0.0"), ("1", "0.0");

CREATE TABLE spark_catalog.banking.banking1 (Banking_ID string, balance string) USING delta;

INSERT INTO spark_catalog.banking.banking1 VALUES ("0", "0.0");

-- Freshness LakeVilla
DROP NAMESPACE freshness CASCADE;
CREATE NAMESPACE freshness;

CREATE TABLE spark_catalog.freshness.table (FRESH_KEY int) USING delta;

-- Freshness Spark
DROP NAMESPACE freshnessSpark CASCADE;
CREATE NAMESPACE freshnessSpark;

CREATE TABLE spark_catalog.freshnessSpark.table (TS long, FRESH_KEY int) USING delta;

-- CAB LakeVilla
DROP NAMESPACE t1 CASCADE;
DROP NAMESPACE t2 CASCADE;
DROP NAMESPACE t3 CASCADE;
DROP NAMESPACE t4 CASCADE;
DROP NAMESPACE t5 CASCADE;
DROP NAMESPACE t6 CASCADE;
DROP NAMESPACE t7 CASCADE;
DROP NAMESPACE t8 CASCADE;
DROP NAMESPACE t9 CASCADE;
DROP NAMESPACE t10 CASCADE;
DROP NAMESPACE t11 CASCADE;
DROP NAMESPACE t12 CASCADE;
DROP NAMESPACE t13 CASCADE;
DROP NAMESPACE t14 CASCADE;
DROP NAMESPACE t15 CASCADE;
DROP NAMESPACE t16 CASCADE;

CREATE NAMESPACE t1;
CREATE NAMESPACE t2;
CREATE NAMESPACE t3;
CREATE NAMESPACE t4;
CREATE NAMESPACE t5;
CREATE NAMESPACE t6;
CREATE NAMESPACE t7;
CREATE NAMESPACE t8;
CREATE NAMESPACE t9;
CREATE NAMESPACE t10;
CREATE NAMESPACE t11;
CREATE NAMESPACE t12;
CREATE NAMESPACE t13;
CREATE NAMESPACE t14;
CREATE NAMESPACE t15;
CREATE NAMESPACE t16;

-- Generate and import TPC-H data!


